/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XkovalcikcAmbulanceWlList {
    }
}
declare global {
    interface HTMLXkovalcikcAmbulanceWlListElement extends Components.XkovalcikcAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXkovalcikcAmbulanceWlListElement: {
        prototype: HTMLXkovalcikcAmbulanceWlListElement;
        new (): HTMLXkovalcikcAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xkovalcikc-ambulance-wl-list": HTMLXkovalcikcAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XkovalcikcAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xkovalcikc-ambulance-wl-list": XkovalcikcAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xkovalcikc-ambulance-wl-list": LocalJSX.XkovalcikcAmbulanceWlList & JSXBase.HTMLAttributes<HTMLXkovalcikcAmbulanceWlListElement>;
        }
    }
}
